apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: key-management-service
  labels:
    cloud.googleapis.com/location: asia-northeast1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/container-dependencies: '{"key-management-service":["cloud-sql-proxy"]}'
    spec:
      serviceAccountName: key-management-service@genai-agent-engine.iam.gserviceaccount.com
      containers:
      - image: asia-northeast1-docker.pkg.dev/genai-agent-engine/key-management-service/key-management-service:latest
        name: key-management-service
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "key-manager:P@ssw0rd!@tcp(127.0.0.1:3306)/key_management?parseTime=true"
        - name: KMS_KEY_NAME
          value: "projects/genai-agent-engine/locations/asia-northeast1/keyRings/key-management/cryptoKeys/kek"
        - name: GOOGLE_CLOUD_PROJECT
          value: "genai-agent-engine"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      - image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.20.0
        name: cloud-sql-proxy
        args:
        - "--address=0.0.0.0"
        - "--port=3306"
        - "genai-agent-engine:asia-northeast1:key-management"
        startupProbe:
         tcpSocket:
           port: 3306
        resources:
          limits:
            memory: 256Mi
            cpu: 1000m
